Fix the post-merge git hook

diff --git a/dev/hooks/post-merge b/dev/hooks/post-merge
--- a/dev/hooks/post-merge
+++ b/dev/hooks/post-merge
@@ -1,5 +1,20 @@
 #!/usr/bin/env bash
 
-ROOT_DIR=$(git rev-parse --show-toplevel)
 # Run composer install
-${ROOT_DIR}/composer install --prefer-dist --ignore-platform-reqs --optimize-autoloader
+COMPOSER_CMD="install --prefer-dist --ignore-platform-reqs --optimize-autoloader"
+COMPOSER_NAMES=("composer.phar" "composer")
+
+for name in ${COMPOSER_NAMES[@]}
+do
+    COMPOSER_PATH=$(which $name)
+    STATUS=$?
+    if [ $STATUS -eq 0 ] && [ -x $COMPOSER_PATH ]; then
+        echo "Composer found in: $COMPOSER_PATH"
+        $COMPOSER_PATH $COMPOSER_CMD
+        break
+    fi
+done
+
+if [ -z $COMPOSER_PATH ]; then
+    echo "WARNING: Composer NOT found"
+fi
